# Generated by Django 2.0.6 on 2018-06-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
