# Generated by Django 2.0.6 on 2018-06-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_auto_20180624_0639'),
        ('Pizza', '0002_auto_20180624_0622'),
    ]

    operations = [
    ]
