# Generated by Django 2.0.4 on 2018-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('aro', models.CharField(max_length=120)),
                ('Estado', models.CharField(max_length=120)),
                ('Tipo', models.CharField(max_length=120)),
                ('Codigo', models.CharField(max_length=120)),
                ('Monto_garantia', models.PositiveIntegerField()),
                ('Imagen', models.ImageField(upload_to='logos')),
            ],
        ),
    ]
